language:
  - cpp

before_install:
  - pip install --user cpp-coveralls
  
addons:
  sonarcloud:
    organization: "dmitry-creator"

script:
  - qmake
  - make
  - ./tests/tests

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"

notifications:
  email: false
